name: CICD
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
       contents: read
       packages: write
       id-token: write
    steps:
      # https://github.com/internetarchive/build/blob/main/action.yml
      - uses: internetarchive/build@v1
        with:
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  image-test:
    runs-on: ubuntu-latest
    needs: [build]
    container:
      # test using the just built-and-pushed docker image from the [build] job above
      image: 'docker://ghcr.io/${{ github.repository }}:${{ github.ref_name }}'
    steps:
    - run: fgrep 'hello js' /app/index.js

  lint:
    runs-on: ubuntu-latest
    container:
      # https://github.com/internetarchive/dyno
      image: ghcr.io/internetarchive/dyno:main
    steps:
    - uses: actions/checkout@v2
    - run: /app/lint

  test:
    runs-on: ubuntu-latest
    container:
      # https://github.com/internetarchive/dyno
      image: ghcr.io/internetarchive/dyno:main
    steps:
    - uses: actions/checkout@v2
    - run: /app/test/test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [build, image-test, lint, test]
    permissions:
       packages: read
    steps:
      # https://github.com/internetarchive/deploy/blob/main/action.yml
      - uses: internetarchive/deploy@v1
        with:
          BASE_DOMAIN: 'dev.archive.org'
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
