name: CICD
on: push
defaults:
  runs-on: ubuntu-latest

jobs:
  build:
    permissions:
       contents: read
       packages: write
       id-token: write
    steps:
      # https://github.com/internetarchive/build/blob/main/action.yml
      - uses: internetarchive/build@v1
        with:
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    needs: [build]
    container:
      # https://github.com/internetarchive/dyno
      image: ghcr.io/internetarchive/dyno:main
    steps:
    - uses: actions/checkout@v2
    - run: /app/lint

  test:
    needs: [build]
    container:
      # https://github.com/internetarchive/dyno
      image: ghcr.io/internetarchive/dyno:main
    steps:
    - uses: actions/checkout@v2
    - run: /app/test/test.sh

  deploy:
    needs: [build, lint, test]
    steps:
      # https://github.com/internetarchive/deploy/blob/main/action.yml
      - uses: internetarchive/deploy@v1
        with:
          BASE_DOMAIN: 'dev.archive.org'
          NOMAD_ADDR: 'https://nom.us.archive.org:4646'
          NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
